#!/bin/bash
# Solution by David Eccles
# Same as loca, but uses perl to parse output
csplit --digits=1 --quiet --prefix=seq $1 "/>.*/" "{*}"
for j in 1 2; do
    sed '1d' seq$j > tmp && mv tmp seq$j;
done;
rm -f seq0
cat seq1 seq2
matcher -datafile=EBLOSUM62 -gapopen 11 -gapextend 1 -aformat3 markx1  seq1 seq2 out
cat out

matcher -datafile=EBLOSUM62 -gapopen 11 -gapextend 1 -aformat3 markx10 seq1 seq2 /dev/fd/1 2>/dev/null | grep -e "^# Score" -e "^[A-Z\-]\+$" -e "^> " | perl -pe 's/\n//;s/> \.\./\n/'| perl -pe 's/\-//g;s/# Score: //'
echo
rm seq1 seq2
