#!/bin/bash
# Rosalind problem LOCA solution by delegation to a library

# Run local alignment program (from EMBOSS suite)
matcher -gapopen 5 -gapextend 5 -datafile pam250.dat $1 $2 -outfile out -aformat markx3 >& /dev/null

# Print score
echo `grep -m 1 Score out | awk '{print $3}'`

# Print aligned sub-strings
grep -v "#---------------------------------------" out > tmp && mv tmp out
csplit --digits=1 --quiet --prefix=out-part out "/>\s\.\./+1" "{*}"
sed -e 's/>\s\.\.//g' out-part1 > tmp && mv tmp out-part1
paste -s out-part1 | tr -d '\t' | tr -d '-'
paste -s out-part2 | tr -d '\t' | tr -d '-'

# Print alignment result
#printf "'%s','%s'\n" `paste -s out-part1 | tr -d '\t'` `paste -s out-part2 | tr -d '\t'`
