'''
============================================================
http://rosalind.info/problems/fibo/

Problem

The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,... are
generated by the following simple rule
F(n)={ F(n-1)+F(n-2),1,0,n>1,n=1,n=0.}

Given: A positive integer n <= 25.

Return: The value of Fn.

Source: Algorithms by Dasgupta, Papadimitriou, Vazirani.
McGraw-Hill. 2006.
============================================================
'''
from rosalind.rosutil import read_int
import itertools as it

def fibonacci(f1=1L, f2=1L):
    '''Fibonacci sequence generator.'''
    yield f1; yield f2
    while True:
        f1, f2 = f2, f1 + f2
        yield f2
    
def fibo(file_name):
    '''Main call.'''
    n = read_int(file_name) 
    print '%d' % (it.islice(fibonacci(), n - 1, n).next(),)
    
if __name__ == "__main__":
    fibo('rosalind_fibo_sample.dat')
    fibo('rosalind_fibo.dat')
